# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6e2100298fa715ccb7d842981a8d2df1a7f1fc97383ab3c077b7b2b2207c6e51ce4997fa8e30744dbabf79250f460818400e204e1153a1be436374c977ebda5

test:
  secret_key_base: a02b91d99ecadbd37f7080f498fa0495c064506625f98eaf7a5ad061720444ac5712ee82d30c88f9b5d0b43c12a2078e383851655fbb2849801643106da9b5dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
